# Generated by Django 4.2.4 on 2023-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_datecreation_comment_datacreation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userPost',
            new_name='commentUser',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dataCreation',
            new_name='dateCreations',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dataCreations',
            new_name='dateCreation',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2),
        ),
    ]
